//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mordhau_Map_Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mordhau_Map_Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyBWnzD_EO6ZVrj4w5gzjwUNWG83FFexYRc.
        /// </summary>
        internal static string google_api_key {
            get {
                return ResourceManager.GetString("google_api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string str_About {
            get {
                return ResourceManager.GetString("str_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All maps installed - You may need to restart Mordhau.
        /// </summary>
        internal static string str_All_maps_installed_You_may_need_to {
            get {
                return ResourceManager.GetString("str_All_maps_installed_You_may_need_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author(s).
        /// </summary>
        internal static string str_Author {
            get {
                return ResourceManager.GetString("str_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Maps.
        /// </summary>
        internal static string str_Available_Maps {
            get {
                return ResourceManager.GetString("str_Available_Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Help.
        /// </summary>
        internal static string str_Basic_Help {
            get {
                return ResourceManager.GetString("str_Basic_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning install for .
        /// </summary>
        internal static string str_Beginning_install_for {
            get {
                return ResourceManager.GetString("str_Beginning_install_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string str_Browse {
            get {
                return ResourceManager.GetString("str_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string str_Cancel {
            get {
                return ResourceManager.GetString("str_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes:.
        /// </summary>
        internal static string str_Changes {
            get {
                return ResourceManager.GetString("str_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string str_Check_for_Updates {
            get {
                return ResourceManager.GetString("str_Check_for_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact a Moderator or @D.Mentia in Discord for help.
        /// </summary>
        internal static string str_Contact_Moderator_or_Mentia_in {
            get {
                return ResourceManager.GetString("str_Contact_Moderator_or_Mentia_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by D.Mentia © 2019.
        /// </summary>
        internal static string str_Created_by_Mentia {
            get {
                return ResourceManager.GetString("str_Created_by_Mentia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show on minor updates.
        /// </summary>
        internal static string str_Don_show_on_minor_updates {
            get {
                return ResourceManager.GetString("str_Don_show_on_minor_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string str_Downloading_name_as_folderName_zip {
            get {
                return ResourceManager.GetString("str_Downloading_name_as_folderName_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating maps.  File -&gt; Refresh to try again.
        /// </summary>
        internal static string str_Error_while_updating_maps_File {
            get {
                return ResourceManager.GetString("str_Error_while_updating_maps_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string str_Exit {
            get {
                return ResourceManager.GetString("str_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed during installation: .
        /// </summary>
        internal static string str_Failed_during_installation_Message {
            get {
                return ResourceManager.GetString("str_Failed_during_installation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for updates.
        /// </summary>
        internal static string str_Failed_to_check_for_updates {
            get {
                return ResourceManager.GetString("str_Failed_to_check_for_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string str_File {
            get {
                return ResourceManager.GetString("str_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        internal static string str_File_Size {
            get {
                return ResourceManager.GetString("str_File_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For extended help, visit the .
        /// </summary>
        internal static string str_For_extended_help_visit_the {
            get {
                return ResourceManager.GetString("str_For_extended_help_visit_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Mordhau Mapping &amp;&amp; Modding.
        /// </summary>
        internal static string str_For_Mordhau_Mapping_Modding {
            get {
                return ResourceManager.GetString("str_For_Mordhau_Mapping_Modding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filenames/Description.
        /// </summary>
        internal static string str_GameModes_Description {
            get {
                return ResourceManager.GetString("str_GameModes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string str_Help {
            get {
                return ResourceManager.GetString("str_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not see any available maps or encounter any bugs, please contact Moderators on Discord.
        /// </summary>
        internal static string str_If_you_do_not_see_any_available_maps_or {
            get {
                return ResourceManager.GetString("str_If_you_do_not_see_any_available_maps_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string str_Install {
            get {
                return ResourceManager.GetString("str_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Map.
        /// </summary>
        internal static string str_Installed_Map {
            get {
                return ResourceManager.GetString("str_Installed_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Maps.
        /// </summary>
        internal static string str_Installed_Maps {
            get {
                return ResourceManager.GetString("str_Installed_Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mordhau Path, please re-enter through Settings.
        /// </summary>
        internal static string str_Invalid_Mordhau_Path_please_re_enter {
            get {
                return ResourceManager.GetString("str_Invalid_Mordhau_Path_please_re_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mordhau path!  Re-set it in Settings before doing anything.
        /// </summary>
        internal static string str_Invalid_Mordhau_path_Re_set_it_in {
            get {
                return ResourceManager.GetString("str_Invalid_Mordhau_path_Re_set_it_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mordhau Path!  Re-set through Settings.
        /// </summary>
        internal static string str_Invalid_Mordhau_Path_Re_set_through {
            get {
                return ResourceManager.GetString("str_Invalid_Mordhau_Path_Re_set_through", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Name.
        /// </summary>
        internal static string str_Map_Name {
            get {
                return ResourceManager.GetString("str_Map_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mordhau Community Maps Installer.
        /// </summary>
        internal static string str_Mordhau_Community_Maps_Installer {
            get {
                return ResourceManager.GetString("str_Mordhau_Community_Maps_Installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version:.
        /// </summary>
        internal static string str_New_Version {
            get {
                return ResourceManager.GetString("str_New_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of MCMI has been detected.
        /// </summary>
        internal static string str_newer_version_of_MCMI_has_been {
            get {
                return ResourceManager.GetString("str_newer_version_of_MCMI_has_been", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates found.
        /// </summary>
        internal static string str_No_updates_found {
            get {
                return ResourceManager.GetString("str_No_updates_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string str_OK {
            get {
                return ResourceManager.GetString("str_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have downloaded the update, you should delete this version.
        /// </summary>
        internal static string str_Once_you_have_downloaded_the_update {
            get {
                return ResourceManager.GetString("str_Once_you_have_downloaded_the_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the location of your BASE Mordhau installation - not the maps folder.
        /// </summary>
        internal static string str_Please_select_the_location_of_your {
            get {
                return ResourceManager.GetString("str_Please_select_the_location_of_your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string str_Ready {
            get {
                return ResourceManager.GetString("str_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string str_Refresh {
            get {
                return ResourceManager.GetString("str_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Failed.
        /// </summary>
        internal static string str_Refresh_Failed {
            get {
                return ResourceManager.GetString("str_Refresh_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        internal static string str_Release_Date {
            get {
                return ResourceManager.GetString("str_Release_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string str_Remove {
            get {
                return ResourceManager.GetString("str_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click on either installed or available maps to Select All or Select None.
        /// </summary>
        internal static string str_Right_click_on_either_installed_or {
            get {
                return ResourceManager.GetString("str_Right_click_on_either_installed_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string str_Save {
            get {
                return ResourceManager.GetString("str_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string str_Select_All {
            get {
                return ResourceManager.GetString("str_Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        internal static string str_Select_None {
            get {
                return ResourceManager.GetString("str_Select_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Mordhau folder, usually under Steam/SteamApps/Common.
        /// </summary>
        internal static string str_Select_your_Mordhau_folder_usually {
            get {
                return ResourceManager.GetString("str_Select_your_Mordhau_folder_usually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Mordhau Directory.
        /// </summary>
        internal static string str_Set_Mordhau_Directory {
            get {
                return ResourceManager.GetString("str_Set_Mordhau_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string str_Settings {
            get {
                return ResourceManager.GetString("str_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some maps contain multiple gamemodes; check the Description to get their names.
        /// </summary>
        internal static string str_Some_maps_contain_multiple_gamemodes {
            get {
                return ResourceManager.GetString("str_Some_maps_contain_multiple_gamemodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted .
        /// </summary>
        internal static string str_Successfully_deleted_name {
            get {
                return ResourceManager.GetString("str_Successfully_deleted_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully installed .
        /// </summary>
        internal static string str_Successfully_installed_name {
            get {
                return ResourceManager.GetString("str_Successfully_installed_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Players.
        /// </summary>
        internal static string str_Suggested_Players {
            get {
                return ResourceManager.GetString("str_Suggested_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message will show once, and can be accessed through the Help menu.
        /// </summary>
        internal static string str_This_message_will_show_once_and_can_be {
            get {
                return ResourceManager.GetString("str_This_message_will_show_once_and_can_be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To play installed maps locally, open the Mordhau console and type &quot;open MapName&quot;.
        /// </summary>
        internal static string str_To_play_installed_maps_locally_open {
            get {
                return ResourceManager.GetString("str_To_play_installed_maps_locally_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string str_Update {
            get {
                return ResourceManager.GetString("str_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string str_Version {
            get {
                return ResourceManager.GetString("str_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Mordhau Community Map Installer.
        /// </summary>
        internal static string str_Welcome_to_the_Mordhau_Community_Map {
            get {
                return ResourceManager.GetString("str_Welcome_to_the_Mordhau_Community_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will sometimes need to restart Mordhau after installing maps, if it&apos;s already open.
        /// </summary>
        internal static string str_You_will_sometimes_need_to_restart {
            get {
                return ResourceManager.GetString("str_You_will_sometimes_need_to_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Version: .
        /// </summary>
        internal static string str_Your_Version {
            get {
                return ResourceManager.GetString("str_Your_Version", resourceCulture);
            }
        }
    }
}
